// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEbz4bGPujRv7jtzeBqDHbbSeYptN2S_8',
    appId: '1:874668964337:web:c7344f5ca899bbc308ac50',
    messagingSenderId: '874668964337',
    projectId: 'note-loom',
    authDomain: 'note-loom.firebaseapp.com',
    storageBucket: 'note-loom.appspot.com',
    measurementId: 'G-8JZK230JLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK_APvSiVCJYwVlQoJqLsLAlhv36P2jcE',
    appId: '1:874668964337:android:2ae7fe4dc72ee53f08ac50',
    messagingSenderId: '874668964337',
    projectId: 'note-loom',
    storageBucket: 'note-loom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZdHytShHotdIXyq3mXgmuJ0rX3aJc1tU',
    appId: '1:874668964337:ios:588ee153145bf34408ac50',
    messagingSenderId: '874668964337',
    projectId: 'note-loom',
    storageBucket: 'note-loom.appspot.com',
    iosClientId: '874668964337-5g8ufkcek8imb1kcc1977q7lbipm9tgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZdHytShHotdIXyq3mXgmuJ0rX3aJc1tU',
    appId: '1:874668964337:ios:e1475fbf0be6f96208ac50',
    messagingSenderId: '874668964337',
    projectId: 'note-loom',
    storageBucket: 'note-loom.appspot.com',
    iosClientId: '874668964337-2gmafr6bucei779qkgojm0imep7ebjdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolApp.RunnerTests',
  );
}
